#version: '3'
services:

  ace-db:
    image: mysql:8.0
    container_name: ace-test-db
    env_file:
      - docker.env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  ace-server:
    build: .
    image: acemulator/ace:latest
    depends_on:
      ace-db:
        condition: service_healthy
    container_name: ace-test-server
    env_file:
      - docker.env
    volumes:
      - ./config:/ace/Config
      - ./content:/ace/Content
      - ./dats:/ace/Dats
      - ./logs:/ace/Logs
      - ./mods:/ace/Mods
    ports:
      - "9000-9001:9000-9001/udp"
    stdin_open: true
    #restart: unless-stopped
    restart: on-failure
